// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/indexer/block/v1/avg_blocktime": {
            "get": {
                "description": "Retrieve the average time taken to mine a block",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Block"
                ],
                "summary": "Get average block time",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.RestBlockTimeAverageResponse"
                        }
                    }
                }
            }
        },
        "/indexer/block/v1/latest_block_height": {
            "get": {
                "description": "Retrieve the latest block height",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Block"
                ],
                "summary": "Get latest block height",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.RestBlockHeightLatestResponse"
                        }
                    }
                }
            }
        },
        "/indexer/tx/v1/txs": {
            "get": {
                "description": "Retrieve a list of transactions with pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction"
                ],
                "summary": "Get transactions",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset for pagination",
                        "name": "pagination.offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Limit for pagination",
                        "name": "pagination.limit",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Reverse order for pagination",
                        "name": "pagination.reverse",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Count total number of transactions",
                        "name": "pagination.count_total",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.RestTxsResponse"
                        }
                    }
                }
            }
        },
        "/indexer/tx/v1/txs/count": {
            "get": {
                "description": "Retrieve the total number of transactions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction"
                ],
                "summary": "Get transaction count",
                "responses": {
                    "200": {
                        "description": "Transaction count",
                        "schema": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "/indexer/tx/v1/txs/{tx_hash}": {
            "get": {
                "description": "Retrieve transaction details by its hash",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction"
                ],
                "summary": "Get transaction by hash",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction hash",
                        "name": "tx_hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.TxResponse"
                        }
                    }
                }
            }
        },
        "/nft/v1/collections": {
            "get": {
                "description": "Retrieve a list of NFT collections with optional search and pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NFT"
                ],
                "summary": "Get NFT collections",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search term for filtering collections",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset for pagination",
                        "name": "pagination.offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Limit for pagination",
                        "name": "pagination.limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.NFTCollectionsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "apperror.Response": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status_code": {
                    "type": "integer"
                }
            }
        },
        "dto.NFTCollection": {
            "type": "object",
            "properties": {
                "creator": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "uri": {
                    "type": "string"
                }
            }
        },
        "dto.NFTCollectionsResponse": {
            "type": "object",
            "properties": {
                "collections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.NFTCollection"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/dto.PaginationResponse"
                }
            }
        },
        "dto.PaginationResponse": {
            "type": "object",
            "properties": {
                "next_key": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.RestBlockHeightLatestResponse": {
            "type": "object",
            "properties": {
                "height": {
                    "type": "integer"
                }
            }
        },
        "dto.RestBlockTimeAverageResponse": {
            "type": "object",
            "properties": {
                "avg_block_time": {
                    "type": "number"
                }
            }
        },
        "dto.RestTxsResponse": {
            "type": "object",
            "properties": {
                "pagination": {
                    "$ref": "#/definitions/dto.PaginationResponse"
                },
                "txs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.TxResponse"
                    }
                }
            }
        },
        "dto.TxResponse": {
            "type": "object",
            "properties": {
                "hash": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "is_ibc": {
                    "type": "boolean"
                },
                "is_opinit": {
                    "type": "boolean"
                },
                "is_send": {
                    "type": "boolean"
                },
                "messages": {
                    "type": "array",
                    "items": {}
                },
                "sender": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        }
    },
    "tags": [
        {
            "description": "NFT related endpoints",
            "name": "NFT"
        },
        {
            "description": "Transaction related endpoints",
            "name": "Transaction"
        },
        {
            "description": "Health check endpoints",
            "name": "Health"
        },
        {
            "description": "Root endpoints",
            "name": "Root"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Core Indexer API",
	Description:      "This is the API service for the Core Indexer project",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
