// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/indexer/block/v1/avg_blocktime": {
            "get": {
                "description": "Retrieve the average time taken to mine a block",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Block"
                ],
                "summary": "Get average block time",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.BlockTimeAverageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    }
                }
            }
        },
        "/indexer/block/v1/latest_block_height": {
            "get": {
                "description": "Retrieve the latest block height",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Block"
                ],
                "summary": "Get latest block height",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.BlockHeightLatestResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    }
                }
            }
        },
        "/indexer/module/v1/modules": {
            "get": {
                "description": "Retrieve a list of modules with pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Module"
                ],
                "summary": "Get modules",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset for pagination",
                        "name": "pagination.offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Limit for pagination",
                        "name": "pagination.limit",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Count total",
                        "name": "pagination.count_total",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ModulesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    }
                }
            }
        },
        "/indexer/module/v1/modules/{vmAddress}/{name}": {
            "get": {
                "description": "Retrieve a module by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Module"
                ],
                "summary": "Get module by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "VM address",
                        "name": "vmAddress",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Module name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ModuleResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    }
                }
            }
        },
        "/indexer/module/v1/modules/{vmAddress}/{name}/histories": {
            "get": {
                "description": "Retrieve a list of module histories with pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Module"
                ],
                "summary": "Get module histories",
                "parameters": [
                    {
                        "type": "string",
                        "description": "VM address",
                        "name": "vmAddress",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Module name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset for pagination",
                        "name": "pagination.offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Limit for pagination",
                        "name": "pagination.limit",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Count total",
                        "name": "pagination.count_total",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ModuleHistoriesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    }
                }
            }
        },
        "/indexer/module/v1/modules/{vmAddress}/{name}/proposals": {
            "get": {
                "description": "Retrieve a module proposal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Module"
                ],
                "summary": "Get module proposal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "VM address",
                        "name": "vmAddress",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Module name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset for pagination",
                        "name": "pagination.offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Limit for pagination",
                        "name": "pagination.limit",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Count total",
                        "name": "pagination.count_total",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ModuleProposalsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    }
                }
            }
        },
        "/indexer/module/v1/modules/{vmAddress}/{name}/publish_info": {
            "get": {
                "description": "Retrieve a module publish info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Module"
                ],
                "summary": "Get module publish info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "VM address",
                        "name": "vmAddress",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Module name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ModulePublishInfoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    }
                }
            }
        },
        "/indexer/module/v1/modules/{vmAddress}/{name}/stats": {
            "get": {
                "description": "Retrieve a module stats",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Module"
                ],
                "summary": "Get module stats by module id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "VM address",
                        "name": "vmAddress",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Module name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ModuleStatsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    }
                }
            }
        },
        "/indexer/module/v1/modules/{vmAddress}/{name}/transactions": {
            "get": {
                "description": "Retrieve a module transaction",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Module"
                ],
                "summary": "Get module transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "VM address",
                        "name": "vmAddress",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Module name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset for pagination",
                        "name": "pagination.offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Limit for pagination",
                        "name": "pagination.limit",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Count total",
                        "name": "pagination.count_total",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ModuleTxsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    }
                }
            }
        },
        "/indexer/nft/v1/collections": {
            "get": {
                "description": "Retrieve a list of NFT collections with optional search and pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NFT"
                ],
                "summary": "Get NFT collections",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search term for filtering collections",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset for pagination",
                        "name": "pagination.offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Limit for pagination",
                        "name": "pagination.limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.NFTCollectionsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    }
                }
            }
        },
        "/indexer/nft/v1/tokens/by_account/{accountAddress}": {
            "get": {
                "description": "Retrieve a list of NFTs owned by a specific account address with optional search and collection filtering",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NFT"
                ],
                "summary": "Get NFTs by account address",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account address of the NFTs owner",
                        "name": "accountAddress",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Search term for filtering NFTs",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Collection address to filter NFTs",
                        "name": "collectionAddress",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset for pagination",
                        "name": "pagination.offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Limit for pagination",
                        "name": "pagination.limit",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Whether to count total NFTs",
                        "name": "pagination.count_total",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.NFTsByAddressResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    }
                }
            }
        },
        "/indexer/nft/v1/tokens/by_collection/{collectionAddress}": {
            "get": {
                "description": "Retrieve a list of NFTs by their collection address with optional search and pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NFT"
                ],
                "summary": "Get NFTs by collection address",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Collection address of the NFTs",
                        "name": "collectionAddress",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Search term for filtering NFTs",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset for pagination",
                        "name": "pagination.offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Limit for pagination",
                        "name": "pagination.limit",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Whether to count total NFTs",
                        "name": "pagination.count_total",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.NFTsByAddressResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    }
                }
            }
        },
        "/indexer/nft/v1/tokens/by_collection/{collectionAddress}/{nftAddress}": {
            "get": {
                "description": "Retrieve a specific NFT by its collection address and NFT address",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NFT"
                ],
                "summary": "Get NFT by collection address and NFT address",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Collection address of the NFT",
                        "name": "collectionAddress",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "NFT address",
                        "name": "nftAddress",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.NFTByAddressResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    }
                }
            }
        },
        "/indexer/proposal/v1/proposals": {
            "get": {
                "description": "Retrieve the list of all proposals",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Proposal"
                ],
                "summary": "Get list of proposals",
                "parameters": [
                    {
                        "type": "string",
                        "default": "",
                        "description": "Filter proposals by proposer",
                        "name": "proposer",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "",
                        "description": "Filter proposals by status(es)",
                        "name": "statuses",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "",
                        "description": "Filter proposals by proposal type",
                        "name": "types",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "",
                        "description": "Search proposals by title or exact proposal id",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ProposalsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    }
                }
            }
        },
        "/indexer/proposal/v1/proposals/types": {
            "get": {
                "description": "Retrieve all submitted proposal types",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Proposal"
                ],
                "summary": "Get list of submitted proposal types",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    }
                }
            }
        },
        "/indexer/proposal/v1/proposals/{proposalId}/answer_counts": {
            "get": {
                "description": "Retrieve vote counts of a proposal by options",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Proposal"
                ],
                "summary": "Get votes count of a proposal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Proposal Id",
                        "name": "proposalId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ProposalAnswerCountsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    }
                }
            }
        },
        "/indexer/proposal/v1/proposals/{proposalId}/info": {
            "get": {
                "description": "Retrieve proposal details",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Proposal"
                ],
                "summary": "Get proposal info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Proposal Id",
                        "name": "proposalId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ProposalInfoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    }
                }
            }
        },
        "/indexer/proposal/v1/proposals/{proposalId}/validator_votes": {
            "get": {
                "description": "Retrieve list of all proposal votes by validators",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Proposal"
                ],
                "summary": "Get validator votes of a proposal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Proposal Id",
                        "name": "proposalId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "",
                        "description": "Search proposal vote by validator moniker or address",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "",
                        "description": "Search proposal votes by vote option",
                        "name": "answer",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ProposalValidatorVotesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    }
                }
            }
        },
        "/indexer/proposal/v1/proposals/{proposalId}/votes": {
            "get": {
                "description": "Retrieve list of all proposal votes",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Proposal"
                ],
                "summary": "Get all proposal votes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Proposal Id",
                        "name": "proposalId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "",
                        "description": "Search proposal vote by voter address",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "",
                        "description": "Search proposal votes by vote option",
                        "name": "answer",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ProposalVotesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    }
                }
            }
        },
        "/indexer/tx/v1/txs": {
            "get": {
                "description": "Retrieve a list of transactions with pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction"
                ],
                "summary": "Get transactions",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset for pagination",
                        "name": "pagination.offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Limit for pagination",
                        "name": "pagination.limit",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Reverse order for pagination",
                        "name": "pagination.reverse",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Count total number of transactions",
                        "name": "pagination.count_total",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.TxsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    }
                }
            }
        },
        "/indexer/tx/v1/txs/count": {
            "get": {
                "description": "Retrieve the total number of transactions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction"
                ],
                "summary": "Get transaction count",
                "responses": {
                    "200": {
                        "description": "Transaction count",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    }
                }
            }
        },
        "/indexer/tx/v1/txs/{tx_hash}": {
            "get": {
                "description": "Retrieve transaction details by its hash",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction"
                ],
                "summary": "Get transaction by hash",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction hash",
                        "name": "tx_hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.TxResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    }
                }
            }
        },
        "/indexer/validator/v1/validators": {
            "get": {
                "description": "Retrieve the list of all validators",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Validator"
                ],
                "summary": "Get list of validators",
                "parameters": [
                    {
                        "type": "boolean",
                        "default": true,
                        "description": "Query for active validators",
                        "name": "is_active",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "",
                        "description": "Sort validators by field: 'uptime', 'commission', 'moniker' or empty for default (voting power)",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "",
                        "description": "Search validators by moniker or exact operator address",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ValidatorsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    }
                }
            }
        },
        "/indexer/validator/v1/validators/{operatorAddr}/answer_counts": {
            "get": {
                "description": "Get validator voted governance proposal answers count",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Validator"
                ],
                "summary": "Get validator proposal answers count",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Validator operator address",
                        "name": "operatorAddr",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ValidatorAnswerCountsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    }
                }
            }
        },
        "/indexer/validator/v1/validators/{operatorAddr}/delegation_related_txs": {
            "get": {
                "description": "Retrieves list of delegation related of a validator",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Validator"
                ],
                "summary": "Get delegation transactions of a validator",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Validator operator address",
                        "name": "operatorAddr",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ValidatorDelegationRelatedTxsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    }
                }
            }
        },
        "/indexer/validator/v1/validators/{operatorAddr}/historical_powers": {
            "get": {
                "description": "Retrieves historical powers of a validator to be rendered",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Validator"
                ],
                "summary": "Get validator historical powers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Validator operator address",
                        "name": "operatorAddr",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ValidatorHistoricalPowersResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    }
                }
            }
        },
        "/indexer/validator/v1/validators/{operatorAddr}/info": {
            "get": {
                "description": "Get validator info from the operator address",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Validator"
                ],
                "summary": "Get validator info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Validator operator address",
                        "name": "operatorAddr",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ValidatorInfoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    }
                }
            }
        },
        "/indexer/validator/v1/validators/{operatorAddr}/proposed_blocks": {
            "get": {
                "description": "Retrieves list of proposed blocks from a validator",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Validator"
                ],
                "summary": "Get validator proposed blocks",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Validator operator address",
                        "name": "operatorAddr",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ValidatorProposedBlocksResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    }
                }
            }
        },
        "/indexer/validator/v1/validators/{operatorAddr}/uptime": {
            "get": {
                "description": "Get validator uptime from the operator address",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Validator"
                ],
                "summary": "Get validator uptime",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Validator operator address",
                        "name": "operatorAddr",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Blocks to be queried",
                        "name": "blocks",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ValidatorUptimeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    }
                }
            }
        },
        "/indexer/validator/v1/validators/{operatorAddr}/voted_proposals": {
            "get": {
                "description": "Retrieves list of voted governance proposals from a validator",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Validator"
                ],
                "summary": "Get validator voted proposals",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Validator operator address",
                        "name": "operatorAddr",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "",
                        "description": "Search validators by moniker or exact operator address",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "",
                        "description": "Filter by given answer",
                        "name": "answer",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ValidatorVotedProposalsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperror.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "apperror.Response": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status_code": {
                    "type": "integer"
                }
            }
        },
        "db.Collection": {
            "type": "object",
            "properties": {
                "block_height": {
                    "type": "integer"
                },
                "creator": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "uri": {
                    "type": "string"
                }
            }
        },
        "dto.AuthInfo": {
            "type": "object",
            "properties": {
                "fee": {
                    "$ref": "#/definitions/dto.Fee"
                },
                "signer_infos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.SignerInfo"
                    }
                }
            }
        },
        "dto.BlockHeightLatestResponse": {
            "type": "object",
            "properties": {
                "height": {
                    "type": "integer"
                }
            }
        },
        "dto.BlockProposer": {
            "type": "object",
            "properties": {
                "identity": {
                    "type": "string"
                },
                "moniker": {
                    "type": "string"
                },
                "operator_address": {
                    "type": "string"
                }
            }
        },
        "dto.BlockTimeAverageResponse": {
            "type": "object",
            "properties": {
                "avg_block_time": {
                    "type": "number"
                }
            }
        },
        "dto.Body": {
            "type": "object",
            "properties": {
                "memo": {
                    "type": "string"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": true
                    }
                },
                "timeout_height": {
                    "type": "string"
                }
            }
        },
        "dto.Coin": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "denom": {
                    "type": "string"
                }
            }
        },
        "dto.Event": {
            "type": "object",
            "properties": {
                "attributes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.EventAttribute"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "dto.EventAttribute": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "dto.Fee": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Coin"
                    }
                },
                "gas_limit": {
                    "type": "string"
                },
                "granter": {
                    "type": "string"
                },
                "payer": {
                    "type": "string"
                }
            }
        },
        "dto.Log": {
            "type": "object",
            "properties": {
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Event"
                    }
                },
                "log": {
                    "description": "Can be string or map[string]string"
                },
                "msg_index": {
                    "type": "integer"
                }
            }
        },
        "dto.MessageType": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                }
            }
        },
        "dto.ModuleHistoriesResponse": {
            "type": "object",
            "properties": {
                "module_histories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ModuleHistoryResponse"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/dto.PaginationResponse"
                }
            }
        },
        "dto.ModuleHistoryResponse": {
            "type": "object",
            "properties": {
                "height": {
                    "type": "integer"
                },
                "previous_policy": {
                    "type": "string"
                },
                "remark": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "timestamp": {
                    "type": "string"
                },
                "upgrade_policy": {
                    "type": "string"
                }
            }
        },
        "dto.ModuleProposalModel": {
            "type": "object",
            "properties": {
                "deposit_end_time": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_emergency": {
                    "type": "boolean"
                },
                "is_expedited": {
                    "type": "boolean"
                },
                "proposer": {
                    "type": "string"
                },
                "resolved_height": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "types": {
                    "type": "string"
                },
                "voting_end_time": {
                    "type": "string"
                }
            }
        },
        "dto.ModuleProposalsResponse": {
            "type": "object",
            "properties": {
                "pagination": {
                    "$ref": "#/definitions/dto.PaginationResponse"
                },
                "proposals": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ModuleProposalModel"
                    }
                }
            }
        },
        "dto.ModulePublishInfoResponse": {
            "type": "object",
            "properties": {
                "is_republished": {
                    "type": "boolean"
                },
                "recent_publish_block_height": {
                    "type": "integer"
                },
                "recent_publish_block_timestamp": {
                    "type": "string"
                },
                "recent_publish_proposal": {
                    "$ref": "#/definitions/dto.Proposal"
                },
                "recent_publish_transaction": {
                    "type": "string"
                }
            }
        },
        "dto.ModuleResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "digest": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "is_republished": {
                    "type": "boolean"
                },
                "is_verified": {
                    "type": "boolean"
                },
                "latest_updated": {
                    "type": "string"
                },
                "module_name": {
                    "type": "string"
                }
            }
        },
        "dto.ModuleStatsResponse": {
            "type": "object",
            "properties": {
                "total_histories": {
                    "type": "integer"
                },
                "total_proposals": {
                    "type": "integer"
                },
                "total_txs": {
                    "type": "integer"
                }
            }
        },
        "dto.ModuleTxResponse": {
            "type": "object",
            "properties": {
                "hash": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "is_ibc": {
                    "type": "boolean"
                },
                "is_move_execute": {
                    "type": "boolean"
                },
                "is_move_execute_event": {
                    "type": "boolean"
                },
                "is_move_publish": {
                    "type": "boolean"
                },
                "is_move_script": {
                    "type": "boolean"
                },
                "is_move_upgrade": {
                    "type": "boolean"
                },
                "is_opinit": {
                    "type": "boolean"
                },
                "is_send": {
                    "type": "boolean"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "sender": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "dto.ModuleTxsResponse": {
            "type": "object",
            "properties": {
                "module_txs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ModuleTxResponse"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/dto.PaginationResponse"
                }
            }
        },
        "dto.ModulesResponse": {
            "type": "object",
            "properties": {
                "modules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ModuleResponse"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/dto.PaginationResponse"
                }
            }
        },
        "dto.NFTByAddressNFTCollectionResponse": {
            "type": "object",
            "properties": {
                "inner": {
                    "type": "string"
                }
            }
        },
        "dto.NFTByAddressNFTResponse": {
            "type": "object",
            "properties": {
                "collection": {
                    "$ref": "#/definitions/dto.NFTByAddressNFTCollectionResponse"
                },
                "description": {
                    "type": "string"
                },
                "is_burned": {
                    "type": "boolean"
                },
                "token_id": {
                    "type": "string"
                },
                "uri": {
                    "type": "string"
                }
            }
        },
        "dto.NFTByAddressResponse": {
            "type": "object",
            "properties": {
                "collection_addr": {
                    "type": "string"
                },
                "collection_name": {
                    "type": "string"
                },
                "nft": {
                    "$ref": "#/definitions/dto.NFTByAddressNFTResponse"
                },
                "object_addr": {
                    "type": "string"
                },
                "owner_addr": {
                    "type": "string"
                }
            }
        },
        "dto.NFTCollectionsResponse": {
            "type": "object",
            "properties": {
                "collections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db.Collection"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/dto.PaginationResponse"
                }
            }
        },
        "dto.NFTsByAddressResponse": {
            "type": "object",
            "properties": {
                "pagination": {
                    "$ref": "#/definitions/dto.PaginationResponse"
                },
                "tokens": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.NFTByAddressResponse"
                    }
                }
            }
        },
        "dto.PaginationResponse": {
            "type": "object",
            "properties": {
                "next_key": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.Proposal": {
            "type": "object",
            "properties": {
                "proposal_id": {
                    "type": "integer"
                },
                "proposal_title": {
                    "type": "string"
                }
            }
        },
        "dto.ProposalAnswerCounts": {
            "type": "object",
            "properties": {
                "abstain": {
                    "type": "integer"
                },
                "no": {
                    "type": "integer"
                },
                "no_with_veto": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "weighted": {
                    "type": "integer"
                },
                "yes": {
                    "type": "integer"
                }
            }
        },
        "dto.ProposalAnswerCountsResponse": {
            "type": "object",
            "properties": {
                "all": {
                    "$ref": "#/definitions/dto.ProposalAnswerCounts"
                },
                "validator": {
                    "$ref": "#/definitions/dto.ProposalValidatorAnswerCounts"
                }
            }
        },
        "dto.ProposalContent": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "metadata": {
                    "type": "string"
                }
            }
        },
        "dto.ProposalDeposit": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Coin"
                    }
                },
                "depositor": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "tx_hash": {
                    "type": "string"
                }
            }
        },
        "dto.ProposalInfo": {
            "type": "object",
            "properties": {
                "abstain": {
                    "type": "string"
                },
                "content": {
                    "$ref": "#/definitions/dto.ProposalContent"
                },
                "created_height": {
                    "type": "integer"
                },
                "created_timestamp": {
                    "type": "string"
                },
                "created_tx_hash": {
                    "type": "string"
                },
                "deposit_end_time": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "failed_reason": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_emergency": {
                    "type": "boolean"
                },
                "is_expedited": {
                    "type": "boolean"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "metadata": {
                    "type": "string"
                },
                "no": {
                    "type": "string"
                },
                "no_with_veto": {
                    "type": "string"
                },
                "proposal_deposits": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ProposalDeposit"
                    }
                },
                "proposer": {
                    "type": "string"
                },
                "resolved_height": {
                    "type": "integer"
                },
                "resolved_timestamp": {
                    "type": "string"
                },
                "resolved_total_voting_power": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "submit_time": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "total_deposit": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Coin"
                    }
                },
                "types": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "version": {
                    "type": "string"
                },
                "voting_end_time": {
                    "type": "string"
                },
                "voting_time": {
                    "type": "string"
                },
                "yes": {
                    "type": "string"
                }
            }
        },
        "dto.ProposalInfoResponse": {
            "type": "object",
            "properties": {
                "info": {
                    "$ref": "#/definitions/dto.ProposalInfo"
                }
            }
        },
        "dto.ProposalSummary": {
            "type": "object",
            "properties": {
                "deposit_end_time": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_emergency": {
                    "type": "boolean"
                },
                "is_expedited": {
                    "type": "boolean"
                },
                "proposer": {
                    "type": "string"
                },
                "resolved_height": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "types": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "voting_end_time": {
                    "type": "string"
                }
            }
        },
        "dto.ProposalValidatorAnswerCounts": {
            "type": "object",
            "properties": {
                "abstain": {
                    "type": "integer"
                },
                "did_not_vote": {
                    "type": "integer"
                },
                "no": {
                    "type": "integer"
                },
                "no_with_veto": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_validators": {
                    "type": "integer"
                },
                "weighted": {
                    "type": "integer"
                },
                "yes": {
                    "type": "integer"
                }
            }
        },
        "dto.ProposalValidatorVote": {
            "type": "object",
            "properties": {
                "identity": {
                    "type": "string"
                },
                "moniker": {
                    "type": "string"
                },
                "validator_address": {
                    "type": "string"
                }
            }
        },
        "dto.ProposalValidatorVotesResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ProposalVote"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.ProposalVote": {
            "type": "object",
            "properties": {
                "abstain": {
                    "type": "number"
                },
                "is_vote_weighted": {
                    "type": "boolean"
                },
                "no": {
                    "type": "number"
                },
                "no_with_veto": {
                    "type": "number"
                },
                "proposal_id": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                },
                "tx_hash": {
                    "type": "string"
                },
                "validator": {
                    "$ref": "#/definitions/dto.ProposalValidatorVote"
                },
                "voter": {
                    "type": "string"
                },
                "yes": {
                    "type": "number"
                }
            }
        },
        "dto.ProposalVotesResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ProposalVote"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.ProposalsResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ProposalSummary"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.PublicKey": {
            "type": "object",
            "properties": {
                "@type": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                }
            }
        },
        "dto.SignerInfo": {
            "type": "object",
            "properties": {
                "public_key": {
                    "$ref": "#/definitions/dto.PublicKey"
                },
                "sequence": {
                    "type": "string"
                }
            }
        },
        "dto.Tx": {
            "type": "object",
            "properties": {
                "auth_info": {
                    "$ref": "#/definitions/dto.AuthInfo"
                },
                "body": {
                    "$ref": "#/definitions/dto.Body"
                },
                "signatures": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dto.TxModel": {
            "type": "object",
            "properties": {
                "hash": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "is_ibc": {
                    "type": "boolean"
                },
                "is_opinit": {
                    "type": "boolean"
                },
                "is_send": {
                    "type": "boolean"
                },
                "messages": {
                    "type": "object"
                },
                "sender": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "dto.TxResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "codespace": {
                    "type": "string"
                },
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Event"
                    }
                },
                "gas_used": {
                    "type": "string"
                },
                "gas_wanted": {
                    "type": "string"
                },
                "height": {
                    "type": "string"
                },
                "logs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Log"
                    }
                },
                "raw_log": {
                    "type": "string"
                },
                "timestamp": {
                    "description": "unix time (GMT)",
                    "type": "string"
                },
                "tx": {
                    "$ref": "#/definitions/dto.Tx"
                },
                "txhash": {
                    "type": "string"
                }
            }
        },
        "dto.TxsResponse": {
            "type": "object",
            "properties": {
                "pagination": {
                    "$ref": "#/definitions/dto.PaginationResponse"
                },
                "txs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.TxModel"
                    }
                }
            }
        },
        "dto.ValidatorAnswerCountsResponse": {
            "type": "object",
            "properties": {
                "abstain": {
                    "type": "integer"
                },
                "all": {
                    "type": "integer"
                },
                "did_not_vote": {
                    "type": "integer"
                },
                "no": {
                    "type": "integer"
                },
                "no_with_veto": {
                    "type": "integer"
                },
                "weighted": {
                    "type": "integer"
                },
                "yes": {
                    "type": "integer"
                }
            }
        },
        "dto.ValidatorBlockVoteModel": {
            "type": "object",
            "properties": {
                "height": {
                    "type": "integer"
                },
                "vote": {
                    "type": "string"
                }
            }
        },
        "dto.ValidatorDelegationRelatedTxsResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ValidatorDelegationTransaction"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.ValidatorDelegationTransaction": {
            "type": "object",
            "properties": {
                "height": {
                    "type": "integer"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.MessageType"
                    }
                },
                "sender": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "tokens": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Coin"
                    }
                },
                "tx_hash": {
                    "type": "string"
                }
            }
        },
        "dto.ValidatorHistoricalPowerModel": {
            "type": "object",
            "properties": {
                "hour_rounded_timestamp": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "voting_power": {
                    "type": "string"
                }
            }
        },
        "dto.ValidatorHistoricalPowersResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ValidatorHistoricalPowerModel"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.ValidatorInfo": {
            "type": "object",
            "properties": {
                "account_address": {
                    "type": "string"
                },
                "commission_rate": {
                    "type": "string"
                },
                "consensus_address": {
                    "type": "string"
                },
                "details": {
                    "type": "string"
                },
                "identity": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "is_jailed": {
                    "type": "boolean"
                },
                "moniker": {
                    "type": "string"
                },
                "rank": {
                    "type": "integer"
                },
                "uptime": {
                    "type": "integer"
                },
                "validator_address": {
                    "type": "string"
                },
                "voting_power": {
                    "type": "string"
                },
                "website": {
                    "type": "string"
                }
            }
        },
        "dto.ValidatorInfoResponse": {
            "type": "object",
            "properties": {
                "info": {
                    "$ref": "#/definitions/dto.ValidatorInfo"
                },
                "total_voting_power": {
                    "type": "string"
                }
            }
        },
        "dto.ValidatorProposedBlockModel": {
            "type": "object",
            "properties": {
                "hash": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                },
                "transaction_count": {
                    "type": "integer"
                },
                "validator": {
                    "$ref": "#/definitions/dto.BlockProposer"
                }
            }
        },
        "dto.ValidatorProposedBlocksResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ValidatorProposedBlockModel"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.ValidatorUptimeEventModel": {
            "type": "object",
            "properties": {
                "height": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "dto.ValidatorUptimeResponse": {
            "type": "object",
            "properties": {
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ValidatorUptimeEventModel"
                    }
                },
                "recent_100_blocks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ValidatorBlockVoteModel"
                    }
                },
                "uptime": {
                    "$ref": "#/definitions/dto.ValidatorUptimeSummary"
                }
            }
        },
        "dto.ValidatorUptimeSummary": {
            "type": "object",
            "properties": {
                "missed_blocks": {
                    "type": "integer"
                },
                "proposed_blocks": {
                    "type": "integer"
                },
                "signed_blocks": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.ValidatorVotedProposal": {
            "type": "object",
            "properties": {
                "abstain": {
                    "type": "number"
                },
                "is_emergency": {
                    "type": "boolean"
                },
                "is_expedited": {
                    "type": "boolean"
                },
                "is_vote_weighted": {
                    "type": "boolean"
                },
                "no": {
                    "type": "number"
                },
                "no_with_veto": {
                    "type": "number"
                },
                "proposal_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "tx_hash": {
                    "type": "string"
                },
                "types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "yes": {
                    "type": "number"
                }
            }
        },
        "dto.ValidatorVotedProposalsResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ValidatorVotedProposal"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.ValidatorsMetadata": {
            "type": "object",
            "properties": {
                "active_count": {
                    "type": "integer"
                },
                "inactive_count": {
                    "type": "integer"
                },
                "min_commission_rate": {
                    "type": "string"
                },
                "percent_33_rank": {
                    "type": "integer"
                },
                "percent_66_rank": {
                    "type": "integer"
                },
                "total_voting_power": {
                    "type": "string"
                }
            }
        },
        "dto.ValidatorsResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ValidatorInfo"
                    }
                },
                "metadata": {
                    "$ref": "#/definitions/dto.ValidatorsMetadata"
                },
                "total": {
                    "type": "integer"
                }
            }
        }
    },
    "tags": [
        {
            "description": "Block related endpoints",
            "name": "Block"
        },
        {
            "description": "Health check endpoints",
            "name": "Health"
        },
        {
            "description": "Module related endpoints",
            "name": "Module"
        },
        {
            "description": "NFT related endpoints",
            "name": "NFT"
        },
        {
            "description": "Proposal related endpoints",
            "name": "Proposal"
        },
        {
            "description": "Root endpoints",
            "name": "Root"
        },
        {
            "description": "Transaction related endpoints",
            "name": "Transaction"
        },
        {
            "description": "Validator related endpoints",
            "name": "Validator"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Core Indexer API",
	Description:      "This is the API service for the Core Indexer project",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
