basePath: /
definitions:
  dto.NFTByAddressNFTCollectionResponse:
    properties:
      inner:
        type: string
    type: object
  dto.NFTByAddressNFTResponse:
    properties:
      collection:
        $ref: '#/definitions/dto.NFTByAddressNFTCollectionResponse'
      description:
        type: string
      is_burned:
        type: boolean
      token_id:
        type: string
      uri:
        type: string
    type: object
  dto.NFTByAddressResponse:
    properties:
      collection_addr:
        type: string
      collection_name:
        type: string
      nft:
        $ref: '#/definitions/dto.NFTByAddressNFTResponse'
      object_addr:
        type: string
      owner_addr:
        type: string
    type: object
  dto.NFTCollection:
    properties:
      creator:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      uri:
        type: string
    type: object
  dto.NFTCollectionsResponse:
    properties:
      collections:
        items:
          $ref: '#/definitions/dto.NFTCollection'
        type: array
      pagination:
        $ref: '#/definitions/dto.PaginationResponse'
    type: object
  dto.NFTsByAddressResponse:
    properties:
      pagination:
        $ref: '#/definitions/dto.PaginationResponse'
      tokens:
        items:
          $ref: '#/definitions/dto.NFTByAddressResponse'
        type: array
    type: object
  dto.PaginationResponse:
    properties:
      next_key:
        type: string
      total:
        type: integer
    type: object
  dto.RestBlockHeightLatestResponse:
    properties:
      height:
        type: integer
    type: object
  dto.RestBlockTimeAverageResponse:
    properties:
      avg_block_time:
        type: number
    type: object
  dto.RestTxsResponse:
    properties:
      pagination:
        $ref: '#/definitions/dto.PaginationResponse'
      txs:
        items:
          $ref: '#/definitions/dto.TxResponse'
        type: array
    type: object
  dto.TxResponse:
    properties:
      hash:
        type: string
      height:
        type: integer
      is_ibc:
        type: boolean
      is_opinit:
        type: boolean
      is_send:
        type: boolean
      messages:
        type: object
      sender:
        type: string
      success:
        type: boolean
      timestamp:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is the API service for the Core Indexer project
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Core Indexer API
  version: "1.0"
paths:
  /indexer/block/v1/avg_blocktime:
    get:
      description: Retrieve the average time taken to mine a block
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.RestBlockTimeAverageResponse'
      summary: Get average block time
      tags:
      - Block
  /indexer/block/v1/latest_block_height:
    get:
      description: Retrieve the latest block height
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.RestBlockHeightLatestResponse'
      summary: Get latest block height
      tags:
      - Block
  /indexer/nft/v1/collections:
    get:
      consumes:
      - application/json
      description: Retrieve a list of NFT collections with optional search and pagination
      parameters:
      - description: Search term for filtering collections
        in: query
        name: search
        type: string
      - default: 0
        description: Offset for pagination
        in: query
        name: pagination.offset
        type: integer
      - default: 10
        description: Limit for pagination
        in: query
        name: pagination.limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.NFTCollectionsResponse'
      summary: Get NFT collections
      tags:
      - NFT
  /indexer/nft/v1/tokens/by_account/{accountAddress}:
    get:
      consumes:
      - application/json
      description: Retrieve a list of NFTs owned by a specific account address with
        optional search and collection filtering
      parameters:
      - description: Account address of the NFTs owner
        in: path
        name: accountAddress
        required: true
        type: string
      - description: Search term for filtering NFTs
        in: query
        name: search
        type: string
      - description: Collection address to filter NFTs
        in: query
        name: collectionAddress
        type: string
      - default: 0
        description: Offset for pagination
        in: query
        name: pagination.offset
        type: integer
      - default: 10
        description: Limit for pagination
        in: query
        name: pagination.limit
        type: integer
      - default: false
        description: Whether to count total NFTs
        in: query
        name: pagination.count_total
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.NFTsByAddressResponse'
      summary: Get NFTs by account address
      tags:
      - NFT
  /indexer/nft/v1/tokens/by_collection/{collectionAddress}:
    get:
      consumes:
      - application/json
      description: Retrieve a list of NFTs by their collection address with optional
        search and pagination
      parameters:
      - description: Collection address of the NFTs
        in: path
        name: collectionAddress
        required: true
        type: string
      - description: Search term for filtering NFTs
        in: query
        name: search
        type: string
      - default: 0
        description: Offset for pagination
        in: query
        name: pagination.offset
        type: integer
      - default: 10
        description: Limit for pagination
        in: query
        name: pagination.limit
        type: integer
      - default: false
        description: Whether to count total NFTs
        in: query
        name: pagination.count_total
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.NFTsByAddressResponse'
      summary: Get NFTs by collection address
      tags:
      - NFT
  /indexer/nft/v1/tokens/by_collection/{collectionAddress}/{nftAddress}:
    get:
      consumes:
      - application/json
      description: Retrieve a specific NFT by its collection address and NFT address
      parameters:
      - description: Collection address of the NFT
        in: path
        name: collectionAddress
        required: true
        type: string
      - description: NFT address
        in: path
        name: nftAddress
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.NFTByAddressResponse'
      summary: Get NFT by collection address and NFT address
      tags:
      - NFT
  /indexer/tx/v1/txs:
    get:
      consumes:
      - application/json
      description: Retrieve a list of transactions with pagination
      parameters:
      - default: 0
        description: Offset for pagination
        in: query
        name: pagination.offset
        type: integer
      - default: 10
        description: Limit for pagination
        in: query
        name: pagination.limit
        type: integer
      - default: false
        description: Reverse order for pagination
        in: query
        name: pagination.reverse
        type: boolean
      - default: false
        description: Count total number of transactions
        in: query
        name: pagination.count_total
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.RestTxsResponse'
      summary: Get transactions
      tags:
      - Transaction
  /indexer/tx/v1/txs/{tx_hash}:
    get:
      consumes:
      - application/json
      description: Retrieve transaction details by its hash
      parameters:
      - description: Transaction hash
        in: path
        name: tx_hash
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.TxResponse'
      summary: Get transaction by hash
      tags:
      - Transaction
  /indexer/tx/v1/txs/count:
    get:
      description: Retrieve the total number of transactions
      produces:
      - application/json
      responses:
        "200":
          description: Transaction count
          schema:
            type: integer
      summary: Get transaction count
      tags:
      - Transaction
swagger: "2.0"
tags:
- description: NFT related endpoints
  name: NFT
- description: Transaction related endpoints
  name: Transaction
- description: Health check endpoints
  name: Health
- description: Root endpoints
  name: Root
