basePath: /
definitions:
  apperror.Response:
    properties:
      message:
        type: string
      status_code:
        type: integer
    type: object
  db.Collection:
    properties:
      block_height:
        type: integer
      creator:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      uri:
        type: string
    type: object
  dto.AuthInfo:
    properties:
      fee:
        $ref: '#/definitions/dto.Fee'
      signer_infos:
        items:
          $ref: '#/definitions/dto.SignerInfo'
        type: array
    type: object
  dto.BlockHeightLatestResponse:
    properties:
      height:
        type: integer
    type: object
  dto.BlockTimeAverageResponse:
    properties:
      avg_block_time:
        type: number
    type: object
  dto.Body:
    properties:
      memo:
        type: string
      messages:
        items:
          additionalProperties: true
          type: object
        type: array
      timeout_height:
        type: string
    type: object
  dto.Coin:
    properties:
      amount:
        type: string
      denom:
        type: string
    type: object
  dto.Event:
    properties:
      attributes:
        items:
          $ref: '#/definitions/dto.EventAttribute'
        type: array
      type:
        type: string
    type: object
  dto.EventAttribute:
    properties:
      key:
        type: string
      value:
        type: string
    type: object
  dto.Fee:
    properties:
      amount:
        items:
          $ref: '#/definitions/dto.Coin'
        type: array
      gas_limit:
        type: string
      granter:
        type: string
      payer:
        type: string
    type: object
  dto.Log:
    properties:
      events:
        items:
          $ref: '#/definitions/dto.Event'
        type: array
      log:
        description: Can be string or map[string]string
      msg_index:
        type: integer
    type: object
  dto.ModuleHistoriesResponse:
    properties:
      module_histories:
        items:
          $ref: '#/definitions/dto.ModuleHistoryResponse'
        type: array
      pagination:
        $ref: '#/definitions/dto.PaginationResponse'
    type: object
  dto.ModuleHistoryResponse:
    properties:
      height:
        type: integer
      previous_policy:
        type: string
      remark:
        items:
          type: integer
        type: array
      timestamp:
        type: string
      upgrade_policy:
        type: string
    type: object
  dto.ModuleProposalModel:
    properties:
      deposit_end_time:
        type: string
      id:
        type: integer
      is_emergency:
        type: boolean
      is_expedited:
        type: boolean
      proposer:
        type: string
      resolved_height:
        type: integer
      status:
        type: string
      title:
        type: string
      types:
        type: string
      voting_end_time:
        type: string
    type: object
  dto.ModuleProposalsResponse:
    properties:
      pagination:
        $ref: '#/definitions/dto.PaginationResponse'
      proposals:
        items:
          $ref: '#/definitions/dto.ModuleProposalModel'
        type: array
    type: object
  dto.ModulePublishInfoResponse:
    properties:
      is_republished:
        type: boolean
      recent_publish_block_height:
        type: integer
      recent_publish_block_timestamp:
        type: string
      recent_publish_proposal:
        $ref: '#/definitions/dto.Proposal'
      recent_publish_transaction:
        type: string
    type: object
  dto.ModuleResponse:
    properties:
      address:
        type: string
      digest:
        type: string
      height:
        type: integer
      is_republished:
        type: boolean
      is_verified:
        type: boolean
      latest_updated:
        type: string
      module_name:
        type: string
    type: object
  dto.ModuleTxResponse:
    properties:
      hash:
        type: string
      height:
        type: integer
      is_ibc:
        type: boolean
      is_move_execute:
        type: boolean
      is_move_execute_event:
        type: boolean
      is_move_publish:
        type: boolean
      is_move_script:
        type: boolean
      is_move_upgrade:
        type: boolean
      is_opinit:
        type: boolean
      is_send:
        type: boolean
      messages:
        items:
          type: integer
        type: array
      sender:
        type: string
      success:
        type: boolean
      timestamp:
        type: string
    type: object
  dto.ModuleTxsResponse:
    properties:
      module_txs:
        items:
          $ref: '#/definitions/dto.ModuleTxResponse'
        type: array
      pagination:
        $ref: '#/definitions/dto.PaginationResponse'
    type: object
  dto.ModulesResponse:
    properties:
      modules:
        items:
          $ref: '#/definitions/dto.ModuleResponse'
        type: array
      pagination:
        $ref: '#/definitions/dto.PaginationResponse'
    type: object
  dto.NFTCollectionsResponse:
    properties:
      collections:
        items:
          $ref: '#/definitions/db.Collection'
        type: array
      pagination:
        $ref: '#/definitions/dto.PaginationResponse'
    type: object
  dto.PaginationResponse:
    properties:
      next_key:
        type: string
      total:
        type: integer
    type: object
  dto.Proposal:
    properties:
      proposal_id:
        type: integer
      proposal_title:
        type: string
    type: object
  dto.PublicKey:
    properties:
      '@type':
        type: string
      key:
        type: string
    type: object
  dto.RestTx:
    properties:
      auth_info:
        $ref: '#/definitions/dto.AuthInfo'
      body:
        $ref: '#/definitions/dto.Body'
      signatures:
        items:
          type: string
        type: array
    type: object
  dto.SignerInfo:
    properties:
      public_key:
        $ref: '#/definitions/dto.PublicKey'
      sequence:
        type: string
    type: object
  dto.TxResponse:
    properties:
      code:
        type: integer
      codespace:
        type: string
      events:
        items:
          $ref: '#/definitions/dto.Event'
        type: array
      gas_used:
        type: string
      gas_wanted:
        type: string
      height:
        type: string
      logs:
        items:
          $ref: '#/definitions/dto.Log'
        type: array
      raw_log:
        type: string
      timestamp:
        description: unix time (GMT)
        type: string
      tx:
        $ref: '#/definitions/dto.RestTx'
      txhash:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is the API service for the Core Indexer project
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Core Indexer API
  version: "1.0"
paths:
  /indexer/block/v1/avg_blocktime:
    get:
      description: Retrieve the average time taken to mine a block
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.BlockTimeAverageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.Response'
      summary: Get average block time
      tags:
      - Block
  /indexer/block/v1/latest_block_height:
    get:
      description: Retrieve the latest block height
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.BlockHeightLatestResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.Response'
      summary: Get latest block height
      tags:
      - Block
  /indexer/module/v1/modules:
    get:
      consumes:
      - application/json
      description: Retrieve a list of modules with pagination
      parameters:
      - default: 0
        description: Offset for pagination
        in: query
        name: pagination.offset
        type: integer
      - default: 10
        description: Limit for pagination
        in: query
        name: pagination.limit
        type: integer
      - default: false
        description: Count total
        in: query
        name: pagination.count_total
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ModulesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.Response'
      summary: Get modules
      tags:
      - Module
  /indexer/module/v1/modules/{vmAddress}/{name}:
    get:
      consumes:
      - application/json
      description: Retrieve a module by id
      parameters:
      - description: VM address
        in: query
        name: vmAddress
        required: true
        type: string
      - description: Module name
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ModuleResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.Response'
      summary: Get module by id
      tags:
      - Module
  /indexer/module/v1/modules/{vmAddress}/{name}/histories:
    get:
      consumes:
      - application/json
      description: Retrieve a list of module histories with pagination
      parameters:
      - description: VM address
        in: query
        name: vmAddress
        required: true
        type: string
      - description: Module name
        in: query
        name: name
        required: true
        type: string
      - default: 0
        description: Offset for pagination
        in: query
        name: pagination.offset
        type: integer
      - default: 10
        description: Limit for pagination
        in: query
        name: pagination.limit
        type: integer
      - default: false
        description: Count total
        in: query
        name: pagination.count_total
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ModuleHistoriesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.Response'
      summary: Get module histories
      tags:
      - Module
  /indexer/module/v1/modules/{vmAddress}/{name}/proposals:
    get:
      consumes:
      - application/json
      description: Retrieve a module proposal
      parameters:
      - description: VM address
        in: query
        name: vmAddress
        required: true
        type: string
      - description: Module name
        in: query
        name: name
        required: true
        type: string
      - default: 0
        description: Offset for pagination
        in: query
        name: pagination.offset
        type: integer
      - default: 10
        description: Limit for pagination
        in: query
        name: pagination.limit
        type: integer
      - default: false
        description: Count total
        in: query
        name: pagination.count_total
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ModuleProposalsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.Response'
      summary: Get module proposal
      tags:
      - Module
  /indexer/module/v1/modules/{vmAddress}/{name}/publish_info:
    get:
      consumes:
      - application/json
      description: Retrieve a module publish info
      parameters:
      - description: VM address
        in: query
        name: vmAddress
        required: true
        type: string
      - description: Module name
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ModulePublishInfoResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.Response'
      summary: Get module publish info
      tags:
      - Module
  /indexer/module/v1/modules/{vmAddress}/{name}/transactions:
    get:
      consumes:
      - application/json
      description: Retrieve a module transaction
      parameters:
      - description: VM address
        in: query
        name: vmAddress
        required: true
        type: string
      - description: Module name
        in: query
        name: name
        required: true
        type: string
      - default: 0
        description: Offset for pagination
        in: query
        name: pagination.offset
        type: integer
      - default: 10
        description: Limit for pagination
        in: query
        name: pagination.limit
        type: integer
      - default: false
        description: Count total
        in: query
        name: pagination.count_total
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ModuleTxsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.Response'
      summary: Get module transaction
      tags:
      - Module
  /indexer/tx/v1/txs/{tx_hash}:
    get:
      consumes:
      - application/json
      description: Retrieve transaction details by its hash
      parameters:
      - description: Transaction hash
        in: path
        name: tx_hash
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.TxResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.Response'
      summary: Get transaction by hash
      tags:
      - Transaction
  /indexer/tx/v1/txs/count:
    get:
      description: Retrieve the total number of transactions
      produces:
      - application/json
      responses:
        "200":
          description: Transaction count
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.Response'
      summary: Get transaction count
      tags:
      - Transaction
  /nft/v1/collections:
    get:
      consumes:
      - application/json
      description: Retrieve a list of NFT collections with optional search and pagination
      parameters:
      - description: Search term for filtering collections
        in: query
        name: search
        type: string
      - default: 0
        description: Offset for pagination
        in: query
        name: pagination.offset
        type: integer
      - default: 10
        description: Limit for pagination
        in: query
        name: pagination.limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.NFTCollectionsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.Response'
      summary: Get NFT collections
      tags:
      - NFT
swagger: "2.0"
tags:
- description: NFT related endpoints
  name: NFT
- description: Transaction related endpoints
  name: Transaction
- description: Health check endpoints
  name: Health
- description: Root endpoints
  name: Root
