basePath: /
definitions:
  apperror.Response:
    properties:
      message:
        type: string
      status_code:
        type: integer
    type: object
  dto.AuthInfo:
    properties:
      fee:
        $ref: '#/definitions/dto.Fee'
      signer_infos:
        items:
          $ref: '#/definitions/dto.SignerInfo'
        type: array
    type: object
  dto.BlockHeightLatestResponse:
    properties:
      height:
        type: integer
    type: object
  dto.BlockTimeAverageResponse:
    properties:
      avg_block_time:
        type: number
    type: object
  dto.Body:
    properties:
      memo:
        type: string
      messages:
        items:
          additionalProperties: true
          type: object
        type: array
      timeout_height:
        type: string
    type: object
  dto.Coin:
    properties:
      amount:
        type: string
      denom:
        type: string
    type: object
  dto.Event:
    properties:
      attributes:
        items:
          $ref: '#/definitions/dto.EventAttribute'
        type: array
      type:
        type: string
    type: object
  dto.EventAttribute:
    properties:
      key:
        type: string
      value:
        type: string
    type: object
  dto.Fee:
    properties:
      amount:
        items:
          $ref: '#/definitions/dto.Coin'
        type: array
      gas_limit:
        type: string
      granter:
        type: string
      payer:
        type: string
    type: object
  dto.Log:
    properties:
      events:
        items:
          $ref: '#/definitions/dto.Event'
        type: array
      log:
        description: Can be string or map[string]string
      msg_index:
        type: integer
    type: object
  dto.NFTCollection:
    properties:
      creator:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      uri:
        type: string
    type: object
  dto.NFTCollectionsResponse:
    properties:
      collections:
        items:
          $ref: '#/definitions/dto.NFTCollection'
        type: array
      pagination:
        $ref: '#/definitions/dto.PaginationResponse'
    type: object
  dto.PaginationResponse:
    properties:
      next_key:
        type: string
      total:
        type: integer
    type: object
  dto.PublicKey:
    properties:
      '@type':
        type: string
      key:
        type: string
    type: object
  dto.RestTx:
    properties:
      auth_info:
        $ref: '#/definitions/dto.AuthInfo'
      body:
        $ref: '#/definitions/dto.Body'
      signatures:
        items:
          type: string
        type: array
    type: object
  dto.SignerInfo:
    properties:
      public_key:
        $ref: '#/definitions/dto.PublicKey'
      sequence:
        type: string
    type: object
  dto.TxResponse:
    properties:
      code:
        type: integer
      codespace:
        type: string
      events:
        items:
          $ref: '#/definitions/dto.Event'
        type: array
      gas_used:
        type: string
      gas_wanted:
        type: string
      height:
        type: string
      logs:
        items:
          $ref: '#/definitions/dto.Log'
        type: array
      raw_log:
        type: string
      timestamp:
        description: unix time (GMT)
        type: string
      tx:
        $ref: '#/definitions/dto.RestTx'
      txhash:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is the API service for the Core Indexer project
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Core Indexer API
  version: "1.0"
paths:
  /indexer/block/v1/avg_blocktime:
    get:
      description: Retrieve the average time taken to mine a block
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.BlockTimeAverageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.Response'
      summary: Get average block time
      tags:
      - Block
  /indexer/block/v1/latest_block_height:
    get:
      description: Retrieve the latest block height
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.BlockHeightLatestResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.Response'
      summary: Get latest block height
      tags:
      - Block
  /indexer/tx/v1/txs/{tx_hash}:
    get:
      consumes:
      - application/json
      description: Retrieve transaction details by its hash
      parameters:
      - description: Transaction hash
        in: path
        name: tx_hash
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.TxResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.Response'
      summary: Get transaction by hash
      tags:
      - Transaction
  /indexer/tx/v1/txs/count:
    get:
      description: Retrieve the total number of transactions
      produces:
      - application/json
      responses:
        "200":
          description: Transaction count
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.Response'
      summary: Get transaction count
      tags:
      - Transaction
  /nft/v1/collections:
    get:
      consumes:
      - application/json
      description: Retrieve a list of NFT collections with optional search and pagination
      parameters:
      - description: Search term for filtering collections
        in: query
        name: search
        type: string
      - default: 0
        description: Offset for pagination
        in: query
        name: pagination.offset
        type: integer
      - default: 10
        description: Limit for pagination
        in: query
        name: pagination.limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.NFTCollectionsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.Response'
      summary: Get NFT collections
      tags:
      - NFT
swagger: "2.0"
tags:
- description: NFT related endpoints
  name: NFT
- description: Transaction related endpoints
  name: Transaction
- description: Health check endpoints
  name: Health
- description: Root endpoints
  name: Root
