basePath: /
definitions:
  dto.ErrorResponse:
    properties:
      code:
        type: integer
      error:
        type: string
    type: object
  dto.NFTCollection:
    properties:
      creator:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      uri:
        type: string
    type: object
  dto.NFTCollectionsResponse:
    properties:
      collections:
        items:
          $ref: '#/definitions/dto.NFTCollection'
        type: array
      pagination:
        $ref: '#/definitions/dto.PaginationResponse'
    type: object
  dto.PaginationResponse:
    properties:
      next_key:
        type: string
      total:
        type: integer
    type: object
host: localhost:3000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is the API service for the Core Indexer project
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Core Indexer API
  version: "1.0"
paths:
  /collections:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.NFTCollectionsResponse'
      summary: Get NFT collections
      tags:
      - NFT
  /indexer/block/v1/avg_blocktime:
    get:
      responses:
        "200":
          description: Average block time in seconds
          schema:
            type: number
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Get average block time
      tags:
      - Block
  /indexer/block/v1/latest_block_height:
    get:
      responses:
        "200":
          description: Latest block height
          schema:
            type: integer
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Get latest block height
      tags:
      - Block
  /indexer/tx/v1/txs/count:
    get:
      responses:
        "200":
          description: Transaction count
          schema:
            type: integer
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Get transaction count
      tags:
      - Tx
swagger: "2.0"
