FROM golang:1.23 AS builder

WORKDIR /informative-indexer
COPY informative-indexer /informative-indexer

RUN go build -o /informative-indexer.bin .

FROM ubuntu:latest

WORKDIR /informative-indexer
COPY --from=builder /informative-indexer.bin /informative-indexer.bin

CMD ["/informative-indexer.bin"]
