FROM golang:1.23 AS builder

WORKDIR /tx-response-uploader
COPY ../tx-response-uploader /tx-response-uploader
COPY ../pkg /pkg

RUN go build -o /tx-response-uploader.bin .

FROM ubuntu:22.04

WORKDIR /tx-response-uploader

RUN apt-get update && apt-get install -y ca-certificates wget

COPY --from=builder /tx-response-uploader.bin /tx-response-uploader.bin

CMD ["/tx-response-uploader.bin"]
