---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-api"
  namespace: {{ quote .Release.Namespace }}
  labels:
    app: "{{ .Release.Name }}-api"
    app.kubernetes.io/name: "{{ .Release.Name }}-api"
    app.kubernetes.io/instance: {{ quote .Release.Name }}
    app.kubernetes.io/version: {{ quote (default "latest" .Chart.AppVersion) }}
    app.kubernetes.io/managed-by: {{ quote .Release.Service }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 6 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.strategy }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  {{- end }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-api"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-api"
    spec:
      {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ quote .Values.serviceAccountName }}
      {{- end }}    
      {{- with .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ quote . }}
      {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - "{{ .Release.Name }}-api"
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: core-indexer-api
          image: {{ quote .Values.image }}
          {{- with .Values.imagePullPolicy }}
          imagePullPolicy: {{ quote . }}
          {{- end }}
          {{- if .Values.env }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ quote $key }}
              value: {{ quote $value }}
            {{- end }}
          {{- end }}
          {{- if .Values.envFrom }}
          envFrom:
            {{- toYaml .Values.envFrom | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
          ports:
            - containerPort: 8080
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
            httpGet:
              path: /health
              port: 8080
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            httpGet:
              path: /health
              port: 8080 
